version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    image: sample-project_frontend:latest # Optional: You can add a tag to ensure you're using the correct image

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
    image: sample-project_backend:latest # Optional: You can add a tag to ensure you're using the correct image
